export const emotions = [
  'happy',
  'playfulness',
  'neutral',
  'guilt',
  'thrilled',
  'pleased',
  'confused',
  'disappointed',
  'friendly',
  'love',
  'envy',
  'compassion',
  'curiosity',
  'tenderness',
  'devotion',
  'angry',
  'resentment',
  'audacious',
  'sadness',
  'anxious',
  'calm',
  'depressed',
];

export const emotionLexicon = {
  happy: ['joy', 'excitement', 'optimism'],
  playfulness: ['amusement'],
  neutral: ['neutral'],
  guilt: ['remorse'],
  thrilled: ['excitement'],
  pleased: ['approval', 'relief'],
  confused: ['confusion', 'realization'],
  disappointed: ['disappointment'],
  friendly: ['caring', 'admiration'],
  love: ['love', 'desire'],
  compassion: ['caring', 'gratitude'],
  envy: ['envy'],
  curiosity: ['curiosity'],
  tenderness: ['caring'],
  devotion: ['admiration'],
  angry: ['anger', 'annoyance', 'disapproval'],
  resentment: ['disgust'],
  audacious: ['amusement'],
  sadness: ['sadness', 'grief', 'disappointment'],
  anxious: ['nervousness', 'fear'],
  calm: ['relief'],
  depressed: ['sadness', 'grief', 'disappointment'],
};
